# Generated by Django 2.0.7 on 2018-08-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20180803_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=30, verbose_name='课程标签'),
        ),
    ]
