# Generated by Django 2.0.7 on 2018-08-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_video_learn_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=20, verbose_name='学习时长(分钟)'),
        ),
    ]
