# Generated by Django 2.0.7 on 2018-08-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20180803_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='course/%Y/%m', verbose_name='封面图'),
        ),
    ]
