"""
Django settings for MxOnline project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))
# 将apps extra_app加入搜索路径

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7b=tl0(z-(4kklb3(fx&bgl*s7^1=zo*n+7bsm@zkpj65a(1h&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['*']


# 设置用户密码或者邮箱均可访问的视图函数配置
AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
)


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'course',
    'operation',
    'organization',
    'xadmin',
    'crispy_forms',
    'captcha',  # 图片验证
    'pure_pagination',  # 列表分页
    'DjangoUeditor'  # 富文本编辑框 https://github.com/zhangfisher/DjangoUeditor
]
AUTH_USER_MODEL = "users.UserProfile"  # UserProfile模型覆盖AbstractModel

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MxOnline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # 将media_url上传文件路径注册到模板中
            ],
        },
    },
]

WSGI_APPLICATION = 'MxOnline.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mxonline',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'  # 后台管理改为中文

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'  # 时区改为上海

USE_I18N = True

USE_L10N = True

# USE_TZ = True  #数据库取为国际时间
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# 生产环境下debug=False，静态文件由http服务器转发，静态文件路径失效
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
 )

MEDIA_URL = '/media/'
# 设置上传文件的路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')   # 指定根目录


# 发送邮件相关配置
EMAIL_HOST = "smtp.163.com"  # 发送邮件服务地址
EMAIL_PORT = 25  # 设置发件服务器端口号。注意，这里有SSL和非SSL两种形式
EMAIL_HOST_USER = "XXXXXX"  # 设置发件服务器端口号。注意，这里有SSL和非SSL两种形式
EMAIL_HOST_PASSWORD = "XXXXXX"  # 邮箱第三方客户端登录授权码 非邮箱密码
EMAIL_USE_TLS = False
EMAIL_FROM = "XXXXXX"  # 邮件发送人

# 自定义分页设置
# https://github.com/jamespacileo/django-pure-pagination
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 8,  # 显示的当前页面附近的页面数（默认值为10）
    'MARGIN_PAGES_DISPLAYED': 2,  # 将显示的第一页和最后一页相邻的页数（默认为2）
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}
