# Generated by Django 2.0.7 on 2018-07-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180724_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='add_tiem',
            new_name='add_time',
        ),
    ]
