# Generated by Django 2.0.7 on 2018-08-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180808_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住址'),
        ),
    ]
